# Generated by Django 3.0.5 on 2020-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=20)),
                ('meal_description', models.TextField()),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='pictures/meal_image/')),
            ],
        ),
    ]
