# Generated by Django 3.0.5 on 2020-04-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200418_0024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Countries',
        ),
    ]
