# Generated by Django 3.0.5 on 2020-04-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200418_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('email_id', models.CharField(max_length=45)),
                ('about_me', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pictures/profile_image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
